# Generated by Django 3.1.4 on 2021-01-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_option_four_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_four',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
